genome_data = {
      'rs12913832': 'GG',
      'rs8177374': 'TT',
      'rs1799971': 'GG',
      'rs806380': 'GG',
      'rs1800955': 'TT',
      'rs53576': 'AA',
      'rs1815739': 'CT',
      'rs6152': 'GG',
      'rs1800497': 'CT',
      'rs9939609': 'AA',
      'rs662799': 'GG',
      'rs17822931': 'CT',
      'rs4680': 'GG',
      'rs4988235': 'TT',
      'rs6025': 'AA',
      'rs7574865': 'TT',
      'rs1695': 'GG',
      'rs72921001': 'AC',
      'rs1537415': 'GG',
      'rs2472297': 'CT',
      'rs909525': 'GG'
}

relatives = [{
      'first_name': "Aodh",
      'last_name': "O'Donnell",
      'sex': "Male",
      'residence': "South Carolina",
      'similarity': 0.25,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1977,
      'relationship': "Brother",
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "Wilder B.",
      'last_name': "O'Donnell",
      'sex': "Male",
      'residence': "Louisiana",
      'similarity': 0.25,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1939,
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      'relationship': "Brother",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "Ruarc",
      'last_name': "O'Donnell",
      'sex': "Male",
      'residence': "North Carolina",
      'similarity': 0.12,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1944,
      'relationship': "1st Cousin",
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },        
      {
      'first_name': "Maximus",
      'last_name': "Bundletreat",
      'sex': "Male",
      'residence': "New Jersey",
      'similarity': 0.125,
      'maternal_side': True,
      'paternal_side': False,
      'birth_year': 1974,
      'relationship': "1st Cousin",
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "Wimberly",
      'last_name': "Carr-Fasheon",
      'sex': "Female",
      'residence': "California",
      'similarity': 0.125,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1983,
      'relationship': "1st Cousin",
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      "picture_url": "http://clipartfreefor.com/cliparts/female-clipart/cliparti1_female-clipart_10.jpg"
      },
      {
      'first_name': "Roberto",
      'last_name': "Carr-Fasheon",
      'sex': "Male",
      'residence': "California",
      'similarity': 0.125,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1983,
      'relationship': "1st Cousin",
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "Mary-Ann",
      'last_name': "Leroy",
      'sex': "Female",
      'residence': "Canada",
      'similarity': 0.06,
      'maternal_side': True,
      'paternal_side': False,
      'birth_year': 1985,
      'relationship': "2nd Cousin",
      "birthplace": "Canada",
      "ancestry": "Northwestern Europe",
      "picture_url": "http://clipartfreefor.com/cliparts/female-clipart/cliparti1_female-clipart_10.jpg"
      },
      {
      'first_name': "Martavius",
      'last_name': "Leroy",
      'sex': "Male",
      'residence': "Canada",
      'similarity': 0.06,
      'maternal_side': True,
      'paternal_side': False,
      'birth_year': 1992,
      'relationship': "2nd Cousin",
      "birthplace": "Canada",
      "ancestry": "Northwestern Europe",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "Alfred",
      'last_name': "Norris",
      'sex': "Male",
      'residence': "Washington",
      'similarity': 0.045,
      'maternal_side': True,
      'paternal_side': False,
      'birth_year': 1980,
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      'relationship': "3rd Cousin",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "James",
      'last_name': "Norris",
      'sex': "Male",
      'residence': "Washington",
      'similarity': 0.045,
      'maternal_side': True,
      'paternal_side': False,
      'birth_year': 1985,
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      'relationship': "3rd Cousin",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "Leonardo",
      'last_name': "Peachfuzz",
      'sex': "Male",
      'residence': "Georgia",
      'similarity': 0.0128,
      'maternal_side': True,
      'paternal_side': False,
      'birth_year': 1980,
      'relationship': "4th-6th Cousin",
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "Quinci",
      'last_name': "Peachfuzz",
      'sex': "Female",
      'residence': "Georgia",
      'similarity': 0.0128,
      'maternal_side': True,
      'paternal_side': False,
      'birth_year': 1966,
      'relationship': "4th-6th Cousin",
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      "picture_url": "http://clipartfreefor.com/cliparts/female-clipart/cliparti1_female-clipart_10.jpg"
      },
      {
      'first_name': "Juniper",
      'last_name': "Kinglsey",
      'sex': "Male",
      'residence': "North Carolina",
      'similarity': 0.0134,
      'maternal_side': True,
      'paternal_side': False,
      'birth_year': 1955,
      "birthplace": "Europe",
      "ancestry": "Northwestern Europe",
      'relationship': "4th Cousin",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "Casseopeia",
      'last_name': "Middlemist-Gilbralter",
      'sex': "Female",
      'residence': "North Carolina",
      'similarity': 0.001,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1978,
      "birthplace": "Canada",
      "ancestry": "Northwestern Europe",
      'relationship': "Distant Relative",
      "picture_url": "http://clipartfreefor.com/cliparts/female-clipart/cliparti1_female-clipart_10.jpg"
      },
      {
      'first_name': "Bartholomew",
      'last_name': "James",
      'sex': "Male",
      'residence': "California",
      'similarity': 0.001,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1969,
      "birthplace": "United States",
      "ancestry": "South African",
      'relationship': "Distant relative",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "Markov",
      'last_name': "Schpeal",
      'sex': "Male",
      'residence': "Russia",
      'similarity': 0.0121,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1970,
      "birthplace": "Russia",
      "ancestry": "Russian",
      'relationship': "4th-6th Cousin",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "Kristen",
      'last_name': "Braile",
      'sex': "Female",
      'residence': "Europe",
      'similarity': 0.0135,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1995,
      "birthplace": "Europe",
      "ancestry": "Northwestern Europe",
      'relationship': "4th Cousin",
      "picture_url": "http://clipartfreefor.com/cliparts/female-clipart/cliparti1_female-clipart_10.jpg"
      },
      {
      'first_name': "Michael",
      'last_name': "Ronaghan",
      'sex': "Male",
      'residence': "New York",
      'similarity': 0.0134,
      'maternal_side': True,
      'paternal_side': False,
      'birth_year': 1963,
      "birthplace": "United States",
      "ancestry": "African-American",
      'relationship': "4th Cousin",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "Chaz",
      'last_name': "Bryant",
      'sex': "Male",
      'residence': "California",
      'similarity': 0.0134,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1972,
      "birthplace": "United States",
      "ancestry": "African-American",
      'relationship': "4th Cousin",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "Wagyu",
      'last_name': "Bryant",
      'sex': "Male",
      'residence': "California",
      'similarity': 0.0134,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1972,
      "birthplace": "United States",
      "ancestry": "African-American",
      'relationship': "4th Cousin",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "Selena",
      'last_name': "Groomez",
      'sex': "Female",
      'residence': "Califonia",
      'similarity': 0.0015,
      'maternal_side': True,
      'paternal_side': False,
      'birth_year': 1993,
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      'relationship': "3rd Cousin",
      "picture_url": "http://clipartfreefor.com/cliparts/female-clipart/cliparti1_female-clipart_10.jpg"
      },
      {
      'first_name': "Harold",
      'last_name': "Nikifor",
      'sex': "Male",
      'residence': "Texas",
      'similarity': 0.001,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1950,
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      'relationship': "Distant relative",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "Justina",
      'last_name': "Fever",
      'sex': "Female",
      'residence': "California",
      'similarity': 0.0015,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1994,
      "birthplace": "Canada",
      "ancestry": "Northwestern Europe",
      'relationship': "3rd Cousin",
      "picture_url": "http://clipartfreefor.com/cliparts/female-clipart/cliparti1_female-clipart_10.jpg"
      },
      {
      'first_name': "Arash",
      'last_name': "Snowama",
      'sex': "Male",
      'residence': "Hawaii",
      'similarity': 0.001,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1950,
      "birthplace": "United States",
      "ancestry": "African-American",
      'relationship': "Distant relative",
      "picture_url": "http://clipartfreefor.com/cliparts/male-clipart/cliparti1_male-clipart_09.jpg"
      },
      {
      'first_name': "Andromeda",
      'last_name': "Middlemist-Gilbralter",
      'sex': "Female",
      'residence': "North Carolina",
      'similarity': 0.002,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1978,
      "birthplace": "Canada",
      "ancestry": "Northwestern Europe",
      'relationship': "Distant Relative",
      "picture_url": "http://clipartfreefor.com/cliparts/female-clipart/cliparti1_female-clipart_10.jpg"
}]