genome_data = {
      'rs12913832': 'GG',
      'rs8177374': 'TT',
      'rs1799971': 'GG',
      'rs806380': 'GG',
      'rs1800955': 'TT',
      'rs53576': 'AA',
      'rs1815739': 'CT',
      'rs6152': 'GG',
      'rs1800497': 'CT',
      'rs9939609': 'AA',
      'rs662799': 'GG',
      'rs17822931': 'CT',
      'rs4680': 'GG',
      'rs4988235': 'TT',
      'rs6025': 'AA',
      'rs7574865': 'TT',
      'rs1695': 'GG',
      'rs72921001': 'AC',
      'rs1537415': 'GG',
      'rs2472297': 'CT',
      'rs909525': 'GG'
}

relatives = [{
      'first_name': "Aodh",
      'last_name': "O'Donnell",
      'sex': "Male",
      'residence': "South Carolina",
      'similarity': 0.25,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1977,
      'relationship': "Brother",
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      "picture_url": "https://goo.gl/0D9cs4"
      },
      {
      'first_name': "Ruarc",
      'last_name': "O'Donnell",
      'sex': "Male",
      'residence': "North Carolina",
      'similarity': 0.12,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1944,
      'relationship': "1st Cousin",
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      "picture_url": "https://goo.gl/0D9cs4"
      },        
      {
      'first_name': "Maximus",
      'last_name': "Bundletreat",
      'sex': "Male",
      'residence': "New Jersey",
      'similarity': 0.125,
      'maternal_side': True,
      'paternal_side': False,
      'birth_year': 1974,
      'relationship': "1st Cousin",
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      "picture_url": "https://goo.gl/0D9cs4"
      },
      {
      'first_name': "Quinci",
      'last_name': "Peachfuzz",
      'sex': "Female",
      'residence': "Georgia",
      'similarity': 0.0128,
      'maternal_side': True,
      'paternal_side': False,
      'birth_year': 1966,
      'relationship': "4th-6th Cousin",
      "birthplace": "United States",
      "ancestry": "Northwestern Europe",
      "picture_url": "https://goo.gl/0D9cs4"
      },
      {
      'first_name': "Wilder B.",
      'last_name': "Shick-Groundswell",
      'sex': "Male",
      'residence': "Louisiana",
      'similarity': 0.25,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1939,
      "birthplace": "France",
      "ancestry": "Northwestern Europe",
      'relationship': "Brother",
      "picture_url": "https://goo.gl/0D9cs4"
      },
      {
      'first_name': "Juniper",
      'last_name': "Kinglsey",
      'sex': "Male",
      'residence': "North Carolina",
      'similarity': 0.0134,
      'maternal_side': True,
      'paternal_side': False,
      'birth_year': 1955,
      "birthplace": "France",
      "ancestry": "Northwestern Europe",
      'relationship': "4th Cousin",
      "picture_url": "https://goo.gl/0D9cs4"
      },
      {
      'first_name': "Casseopeia",
      'last_name': "Middlemist-Gilbralter",
      'sex': "Female",
      'residence': "North Carolina",
      'similarity': 0.002,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1978,
      "birthplace": "Canada",
      "ancestry": "Northwestern Europe",
      'relationship': "Distant Relative",
      "picture_url": "https://goo.gl/0D9cs4"
      },
      {
      'first_name': "Andromeda",
      'last_name': "Middlemist-Gilbralter",
      'sex': "Female",
      'residence': "North Carolina",
      'similarity': 0.002,
      'maternal_side': False,
      'paternal_side': True,
      'birth_year': 1978,
      "birthplace": "Canada",
      "ancestry": "Northwestern Europe",
      'relationship': "Distant Relative",
      "picture_url": "https://goo.gl/0D9cs4"
}]